[package]
name = "type_val"
version = "0.3.3"
authors = ["TurkeyMcMac <jwmhjwmh@gmail.com>"]
description = "Type-level values."
repository = "https://github.com/TurkeyMcMac/type_val"
categories = ["no-std"]
license = "MIT"

[dependencies]
